name: Build

on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  build:
    name: Build and Test TensorNVME
    if: |
      github.event.pull_request.draft == false &&
      github.base_ref == 'main' &&
      github.event.pull_request.base.repo.full_name == 'hpcaitech/TensorNVME' &&
      contains( github.event.pull_request.labels.*.name, 'Run Build and Test')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY_FOR_CI }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.12'
      - name: Install tensornvme
        run: |
          pip install -r requirements.txt
          pip install -v -e .
      - name: Unit Testing
        run: |
          pip install -r tests/requirements.txt
          PYTHONPATH=$PWD pytest tests
        env:
          LD_LIBRARY_PATH: /github/home/.tensornvme/lib
